[tool.poetry]
name = "myenv"
version = "0.1.0"
description = "mcts alpha beta pruning"
authors = ["None"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.2"
hydra-core = "^1.3.1"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
